### ISSUE TITLE
[BUG] windows10部署最新版本，conda环境，xinference运行推理，在RAG对话中选择知识库问答，报错ERROR:    Exception in ASGI application

### ISSUE THREAD

**Issue by HuoShengLiangIT** [chatchat-space/Langchain-Chatchat#4569] opened 2024-07-19 02:14 UTC
**问题描述 / Problem Description**
windows10部署最新版本，conda环境，xinference运行推理，在RAG对话中选择知识库问答，报错ERROR:    Exception in ASGI application
......
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

**预期的结果 / Expected Result**
RAG对话中选择知识库问答，输入**你好**，语气大模型返回打招呼内容

**实际结果 / Actual Result**
实际返回如下内容：
D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\langchain_core\_api\deprecation.py:119: LangChainDeprecationWarning: The method `BaseRetriever.get_relevant_documents` was deprecated in langchain-core 0.1.46 and will be removed in 0.3.0. Use invoke instead.
  warn_deprecated(
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\sse_starlette\sse.py", line 269, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\sse_starlette\sse.py", line 258, in wrap
    await func()
  File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\sse_starlette\sse.py", line 215, in listen_for_disconnect
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 524, in receive
    await self.message_event.wait()
  File "D:\software\anaconda3\envs\chat_source_311\Lib\asyncio\locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 1cdcb5d5590

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\starlette\applications.py", line 123, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
  |     raise exc
  |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
  |     await self.app(scope, receive, send)
  |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\starlette\routing.py", line 758, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\starlette\routing.py", line 778, in app
  |     await route.handle(scope, receive, send)
  |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\starlette\routing.py", line 299, in handle
  |     await self.app(scope, receive, send)
  |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\starlette\routing.py", line 79, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\starlette\routing.py", line 77, in app
  |     await response(scope, receive, send)
  |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\sse_starlette\sse.py", line 255, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\anyio\_backends\_asyncio.py", line 680, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\sse_starlette\sse.py", line 258, in wrap
    |     await func()
    |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\sse_starlette\sse.py", line 245, in stream_response
    |     async for data in self.body_iterator:
    |   File "D:\code\sh\python-project\langchain-chat-new\Langchain-Chatchat\libs\chatchat-server\chatchat\server\chat\kb_chat.py", line 71, in knowledge_base_chat_iterator
    |     docs = await run_in_threadpool(search_docs,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\starlette\concurrency.py", line 42, in run_in_threadpool
    |     return await anyio.to_thread.run_sync(func, *args)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    |     return await get_async_backend().run_sync_in_worker_thread(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    |     return await future
    |            ^^^^^^^^^^^^
    |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    |     result = context.run(func, *args)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\code\sh\python-project\langchain-chat-new\Langchain-Chatchat\libs\chatchat-server\chatchat\server\knowledge_base\kb_doc_api.py", line 70, in search_docs
    |     docs = kb.search_docs(query, top_k, score_threshold)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\code\sh\python-project\langchain-chat-new\Langchain-Chatchat\libs\chatchat-server\chatchat\server\knowledge_base\kb_service\base.py", line 219, in search_docs
    |     docs = self.do_search(query, top_k, score_threshold)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\code\sh\python-project\langchain-chat-new\Langchain-Chatchat\libs\chatchat-server\chatchat\server\knowledge_base\kb_service\milvus_kb_service.py", line 88, in do_search
    |     docs = retriever.get_relevant_documents(query)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\code\sh\python-project\langchain-chat-new\Langchain-Chatchat\libs\chatchat-server\chatchat\server\file_rag\retrievers\vectorstore.py", line 30, in get_relevant_documents
    |     return self.retriever.get_relevant_documents(query)[: self.top_k]
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\langchain_core\_api\deprecation.py", line 148, in warning_emitting_wrapper
    |     return wrapped(*args, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\langchain_core\retrievers.py", line 323, in get_relevant_documents
    |     raise e
    |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\langchain_core\retrievers.py", line 316, in get_relevant_documents
    |     result = self._get_relevant_documents(
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\langchain_core\vectorstores.py", line 699, in _get_relevant_documents
    |     self.vectorstore.similarity_search_with_relevance_scores(
    |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\langchain_core\vectorstores.py", line 323, in similarity_search_with_relevance_scores
    |     docs_and_similarities = self._similarity_search_with_relevance_scores(
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\langchain_core\vectorstores.py", line 270, in _similarity_search_with_relevance_scores
    |     relevance_score_fn = self._select_relevance_score_fn()
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\langchain_core\vectorstores.py", line 227, in _select_relevance_score_fn
    |     raise NotImplementedError
    | NotImplementedError
    +------------------------------------
2024-07-19 09:18:37.311 Uncaught app exception
Traceback (most recent call last):
  File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
    yield
  File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\httpx\_transports\default.py", line 113, in __iter__
    for part in self._httpcore_stream:
  File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\httpcore\_sync\connection_pool.py", line 367, in __iter__
    raise exc from None
  File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\httpcore\_sync\connection_pool.py", line 363, in __iter__
    for part in self._stream:
  File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\httpcore\_sync\http11.py", line 349, in __iter__
    raise exc
  File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\httpcore\_sync\http11.py", line 341, in __iter__
    for chunk in self._connection._receive_response_body(**kwargs):
  File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\httpcore\_sync\http11.py", line 210, in _receive_response_body
    event = self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\httpcore\_sync\http11.py", line 220, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
  File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\openai\_streaming.py", line 46, in __iter__
    for item in self._iterator:
  File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\openai\_streaming.py", line 58, in __stream__
    for sse in iterator:
  File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\openai\_streaming.py", line 50, in _iter_events
    yield from self._decoder.iter_bytes(self.response.iter_bytes())
  File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\openai\_streaming.py", line 280, in iter_bytes
    for chunk in self._iter_chunks(iterator):
  File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\openai\_streaming.py", line 291, in _iter_chunks
    for chunk in iterator:
  File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\httpx\_models.py", line 829, in iter_bytes
    for raw_bytes in self.iter_raw():
  File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\httpx\_models.py", line 883, in iter_raw
    for raw_stream_bytes in self.stream:
  File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\httpx\_client.py", line 126, in __iter__
    for chunk in self._stream:
  File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\httpx\_transports\default.py", line 112, in __iter__
    with map_httpcore_exceptions():
  File "D:\software\anaconda3\envs\chat_source_311\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\software\anaconda3\envs\chat_source_311\Lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

**环境信息 / Environment Information**
- Langchain-Chatchat commit 号：commit/cbfdd72fff619b6cf12bc3eeee51e320cb14de2d
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：qwen1.5-chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-small-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： milvus
- 操作系统及版本 / Operating system and version: windows10
- Python 版本 / Python version: 3.11

**Comment by liunux4odoo** [comment] 2024-07-19 02:36
duplicate of #4525

**Closed by liunux4odoo** 2024-07-19 02:36 UTC
Labels: bug
