### ISSUE TITLE
[BUG] 搜索引擎在web UI的搜索引擎问答那可以正常运行但换到agent上就会报错RemoteProtocolError

### ISSUE THREAD

**Issue by BigWuKing** [chatchat-space/Langchain-Chatchat#4589] opened 2024-07-22 09:34 UTC
**问题描述 / Problem Description**
我想问问就是我在WEB 页面的搜索引擎问答哪里运行搜索引擎metaphor能够正常得出搜索结果但是如果换到agent上的互联网搜索工具运行，没启动agent的情况下就会报错：RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)，启动agent的情况下就会报错ValidationError(model='search_internetSchema', errors=[{'loc': ('query',), 'msg': 'str type expected', 'type': 'type_error.st...
pydantic.v1.error_wrappers.ValidationError: 1 validation error for search_internetSchema
query
str type expected (type=type_error.str)。并且我已经把tool_settings.yaml里的search_engine_name改成了 metaphor，kb_settings.yaml里的DEFAULT_SEARCH_ENGINE 也改成了metaphor，但都不管用，所有想问问有没有人知道这是什么情况应该如何解决。

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.
![微信图片_20240722053311](https://github.com/user-attachments/assets/8faf1ccc-3537-4b34-996f-91b797d24a76)

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
没启动Agent:
    user=None,
    extra_headers=None,
    extra_query=None,
    extra_json=None,
    timeout=None,
    messages=[
        {'content': '人民币兑美元的汇率现在是多少', 'role': 'user'},
        {'role': 'assistant', 'content': '\n1 CNY = 0.20 USD'},
        {'content': '人民币兑美元的汇率现在是多少', 'role': 'user'}
    ],
    model='autodl-tmp-glm-4-9b-chat',
    frequency_penalty=None,
    function_call=None,
    functions=None,
    logit_bias=None,
    logprobs=None,
    max_tokens=None,
    n=None,
    presence_penalty=None,
    response_format=None,
    seed=None,
    stop=None,
    stream=True,
    temperature=0.7,
    tool_choice='search_internet',
    tools=['search_internet'],
    top_logprobs=None,
    top_p=None,
    metadata=None,
    chat_model_config={
        'preprocess_model': {
            'autodl-tmp-glm-4-9b-chat': {
                'model': '',
                'temperature': 0.05,
                'max_tokens': 4096,
                'history_len': 10,
                'prompt_name': 'default',
                'callbacks': False
            }
        },
        'llm_model': {'autodl-tmp-glm-4-9b-chat': {}},
        'action_model': {
            'autodl-tmp-glm-4-9b-chat': {
                'model': '',
                'temperature': 0.01,
                'max_tokens': 4096,
                'history_len': 10,
                'prompt_name': 'ChatGLM3',
                'callbacks': True
            }
        },
        'postprocess_model': {
            'autodl-tmp-glm-4-9b-chat': {
                'model': '',
                'temperature': 0.01,
                'max_tokens': 4096,
                'history_len': 10,
                'prompt_name': 'default',
                'callbacks': True
            }
        },
        'image_model': {'sd-turbo': {'model': 'sd-turbo', 'size': '256*256'}}
    },
    conversation_id='efa2c27ada004a5d9404258a28326cb3',
    tool_input={'query': '人民币兑美元的汇率现在是多少'},
    upload_image=None
)
INFO:     127.0.0.1:39854 - "POST /chat/chat/completions HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/sse_starlette/sse.py", line 269, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/sse_starlette/sse.py", line 258, in wrap
    await func()
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/sse_starlette/sse.py", line 215, in listen_for_disconnect
    message = await receive()
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 524, in receive
    await self.message_event.wait()
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
  |     return await self.app(scope, receive, send)
  |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/starlette/applications.py", line 123, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/starlette/middleware/errors.py", line 186, in __call__
  |     raise exc
  |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/starlette/routing.py", line 758, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/starlette/routing.py", line 778, in app
  |     await route.handle(scope, receive, send)
  |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/starlette/routing.py", line 299, in handle
  |     await self.app(scope, receive, send)
  |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/starlette/routing.py", line 79, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/starlette/routing.py", line 77, in app
  |     await response(scope, receive, send)
  |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/sse_starlette/sse.py", line 269, in __call__
  |     await wrap(partial(self.listen_for_disconnect, receive))
  |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/sse_starlette/sse.py", line 258, in wrap
    |     await func()
    |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/sse_starlette/sse.py", line 245, in stream_response
    |     async for data in self.body_iterator:
    |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/chatchat/server/api_server/openai_routes.py", line 85, in generator
    |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/chatchat/server/api_server/api_schemas.py", line 172, in model_dump_json
    |     return json.dumps(self.model_dump(), ensure_ascii=False)
    |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/chatchat/server/knowledge_base/utils.py", line 146, in _new_json_dumps
    |     return _origin_json_dumps(obj, **kwargs)
    |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/json/__init__.py", line 234, in dumps
    |     return cls(
    |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/json/encoder.py", line 199, in encode
    |     chunks = self.iterencode(o, _one_shot=True)
    |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/json/encoder.py", line 257, in iterencode
    |     return _iterencode(o, 0)
    |   File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/json/encoder.py", line 179, in default
    |     raise TypeError(f'Object of type {o.__class__.__name__} '
    | TypeError: Object of type Document is not JSON serializable
    +------------------------------------
2024-07-22 16:57:28,178 httpx        3774928 INFO     HTTP Request: POST http://127.0.0.1:13366/chat/chat/completions "HTTP/1.1 200 OK"
2024-07-22 16:57:28.178 Uncaught app exception
Traceback (most recent call last):
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/httpx/_transports/default.py", line 113, in __iter__
    for part in self._httpcore_stream:
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py", line 367, in __iter__
    raise exc from None
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py", line 363, in __iter__
    for part in self._stream:
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 349, in __iter__
    raise exc
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 341, in __iter__
    for chunk in self._connection._receive_response_body(**kwargs):
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 210, in _receive_response_body
    event = self._receive_event(timeout=timeout)
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 221, in _receive_event
    event = self._h11_state.next_event()
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/chatchat/webui.py", line 73, in <module>
    dialogue_page(api=api, is_lite=is_lite)
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/chatchat/webui_pages/dialogue/dialogue.py", line 426, in dialogue_page
    stream = not is_vision_chat
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/openai/_streaming.py", line 46, in __iter__
    for item in self._iterator:
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/openai/_streaming.py", line 58, in __stream__
    for sse in iterator:
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/openai/_streaming.py", line 50, in _iter_events
    yield from self._decoder.iter_bytes(self.response.iter_bytes())
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/openai/_streaming.py", line 280, in iter_bytes
    for chunk in self._iter_chunks(iterator):
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/openai/_streaming.py", line 291, in _iter_chunks
    for chunk in iterator:
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/httpx/_models.py", line 829, in iter_bytes
    for raw_bytes in self.iter_raw():
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/httpx/_models.py", line 883, in iter_raw
    for raw_stream_bytes in self.stream:
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/httpx/_client.py", line 126, in __iter__
    for chunk in self._stream:
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/httpx/_transports/default.py", line 114, in __iter__
    yield part
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/x3/miniconda3/envs/chatchat/lib/python3.8/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.3.1.2 / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：否 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：autodl-tmp-glm-4-9b-chat / Model used (ChatGLM2-6B / Qwen-7B, etc.): autodl-tmp-glm-4-9b-chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-small-zh-v1.5 / Embedding model used (moka-ai/m3e-base, etc.): bge-small-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version: Ubuntu 22.04.2 LTS
- Python 版本 / Python version: 3.8
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.
其他工具像是查天气的，计算器，本地知识库都是能正常运行的，就这个互联网搜索有问题

**Comment by BigWuKing** [comment] 2024-07-23 01:56
其他工具像是查天气的，计算器，本地知识库都是能正常运行的，就这个互联网搜索有问题

**Comment by liunux4odoo** [comment] 2024-07-24 13:57
duplicate of #4519

**Closed by liunux4odoo** 2024-07-24 13:57 UTC
Labels: bug
