### ISSUE TITLE
[BUG] 运行server/api.py，报错Error communicating with OpenAI

### ISSUE THREAD

**Issue by luojihaohuawei** [chatchat-space/Langchain-Chatchat#2495] opened 2023-12-28 06:24 UTC
**问题描述 / Problem Description**
运行server/api.py，返回接口，调用接口，后台报错：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/151513501/c3eb366a-c8ea-4632-8566-31437c439986)
请问是OpenAI相关配置没有设置吗？

调用命令：
curl -X 'POST' \
  'http://127.0.0.1:7861/chat/fastchat' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
 "conversation_id ":"0",
  "model": "chatglm3-6b",
  "messages": [
    {
      "role": "user",
      "content": "hello"
    }
  ],
  "temperature": 0.7,
  "n": 1,
  "stop": [],
  "stream": false,
  "presence_penalty": 0,
  "frequency_penalty": 0
}'

**Comment by liunux4odoo** [comment] 2023-12-30 03:55
Duplicate of #2449

**Closed by liunux4odoo** 2023-12-30 03:55 UTC
Labels: bug
