### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by 2408211636** [chatchat-space/Langchain-Chatchat#4909] opened 2024-09-04 02:35 UTC
**问题描述 / Problem Description**
知识库中增加pdf，出错，报告”zipfile.BadZipFile: File is not a zip file“错误

**复现问题的步骤 / Steps to Reproduce**
通过webui界面的”知识库管理“界面中添加pdf文件到知识库中，出现”zipfile.BadZipFile: File is not a zip file“错误

**预期的结果 / Expected Result**
能够添加pdf文件到知识库中，能够预览内容

**实际结果 / Actual Result**
langchain                      0.1.17
langchain-chatchat             0.3.1.3
langchain-community            0.0.36
langchain-core                 0.1.52
langchain-experimental         0.0.58
langchain-openai               0.0.6
langchain-text-splitters       0.0.2
langchainhub                   0.1.14

**异常信息如下：
点？.pdf 加载文档时出错：File is not a zip file
2024-09-04 10:02:43.498 | ERROR    | chatchat.server.knowledge_base.utils:files2docs_in_thread_file2docs:425 - trace back: Traceback (most recent call last):
  File "/home/trader/anaconda3/lib/python3.10/site-packages/chatchat/server/knowledge_base/utils.py", line 421, in files2docs_in_thread_file2docs
    return True, (file.kb_name, file.filename, file.file2text(**kwargs))
  File "/home/trader/anaconda3/lib/python3.10/site-packages/chatchat/server/knowledge_base/utils.py", line 396, in file2text
    docs = self.file2docs()
  File "/home/trader/anaconda3/lib/python3.10/site-packages/chatchat/server/knowledge_base/utils.py", line 351, in file2docs
    self.docs = loader.load()
  File "/home/trader/anaconda3/lib/python3.10/site-packages/langchain_core/document_loaders/base.py", line 29, in load
    return list(self.lazy_load())
  File "/home/trader/anaconda3/lib/python3.10/site-packages/langchain_community/document_loaders/unstructured.py", line 88, in lazy_load
    elements = self._get_elements()
  File "/home/trader/anaconda3/lib/python3.10/site-packages/chatchat/server/file_rag/document_loaders/mypdfloader.py", line 96, in _get_elements
    return partition_text(text=text, **self.unstructured_kwargs)
  File "/home/trader/anaconda3/lib/python3.10/site-packages/unstructured/partition/text.py", line 93, in partition_text
    return _partition_text(
  File "/home/trader/anaconda3/lib/python3.10/site-packages/unstructured/documents/elements.py", line 518, in wrapper
    elements = func(*args, **kwargs)
  File "/home/trader/anaconda3/lib/python3.10/site-packages/unstructured/file_utils/filetype.py", line 591, in wrapper
    elements = func(*args, **kwargs)
  File "/home/trader/anaconda3/lib/python3.10/site-packages/unstructured/file_utils/filetype.py", line 546, in wrapper
    elements = func(*args, **kwargs)
  File "/home/trader/anaconda3/lib/python3.10/site-packages/unstructured/chunking/__init__.py", line 52, in wrapper
    elements = func(*args, **kwargs)
  File "/home/trader/anaconda3/lib/python3.10/site-packages/unstructured/partition/text.py", line 190, in _partition_text
    element = element_from_text(ctext)
  File "/home/trader/anaconda3/lib/python3.10/site-packages/unstructured/partition/text.py", line 235, in element_from_text
    elif is_possible_narrative_text(text):
  File "/home/trader/anaconda3/lib/python3.10/site-packages/unstructured/partition/text_type.py", line 87, in is_possible_narrative_text
    if "eng" in languages and (sentence_count(text, 3) < 2) and (not contains_verb(text)):
  File "/home/trader/anaconda3/lib/python3.10/site-packages/unstructured/partition/text_type.py", line 189, in contains_verb
    pos_tags = pos_tag(text)
  File "/home/trader/anaconda3/lib/python3.10/site-packages/unstructured/nlp/tokenize.py", line 44, in pos_tag
    _download_nltk_package_if_not_present(
  File "/home/trader/anaconda3/lib/python3.10/site-packages/unstructured/nlp/tokenize.py", line 21, in _download_nltk_package_if_not_present
    nltk.find(f"{package_category}/{package_name}")
  File "/home/trader/anaconda3/lib/python3.10/site-packages/nltk/data.py", line 555, in find
    return find(modified_name, paths)
  File "/home/trader/anaconda3/lib/python3.10/site-packages/nltk/data.py", line 542, in find
    return ZipFilePathPointer(p, zipentry)
  File "/home/trader/anaconda3/lib/python3.10/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/home/trader/anaconda3/lib/python3.10/site-packages/nltk/data.py", line 394, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/home/trader/anaconda3/lib/python3.10/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/home/trader/anaconda3/lib/python3.10/site-packages/nltk/data.py", line 935, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/home/trader/anaconda3/lib/python3.10/zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "/home/trader/anaconda3/lib/python3.10/zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by liunux4odoo** [comment] 2024-09-04 07:17
duplicate of #4831

**Closed by liunux4odoo** 2024-09-04 07:17 UTC
Labels: bug
