### ISSUE TITLE
知识库问答某个函数参数数量报错

### ISSUE THREAD

**Issue by Zou-njust** [chatchat-space/Langchain-Chatchat#1562] opened 2023-09-22 02:08 UTC
TypeError: ChatBox.update_msg() takes from 1 to 2 positional arguments but 3 were given
Traceback:
File "/root/anaconda3/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
File "/home/chatglm2-6b/Langchain-Chatchat/webui.py", line 66, in <module>
    pages[selected_page]["func"](api)
File "/home/chatglm2-6b/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 166, in dialogue_page
    chat_box.update_msg(text, 0)

不知道是不是python和包的版本问题，之前在另一个版本的python中没有报错

**Comment by Zou-njust** [comment] 2023-09-22 02:16
修改streamlit_chatbox包版本在requirements.txt要求的范围里，已经解决，可能是之前pip install -r requirements.txt有冲突还是用了清华镜像的原因

**Comment by liunux4odoo** [comment] 2023-09-23 11:12
Duplicate of #1578

**Closed by liunux4odoo** 2023-09-23 11:12 UTC
Labels: bug
