### ISSUE TITLE
KeyError: 'finished' in knowledge_base_page     empty.progress(d["finished"] / d["total"], f"正在处理： {d['doc']}")

### ISSUE THREAD

**Issue by zdj-1995** [chatchat-space/Langchain-Chatchat#1179] opened 2023-08-21 08:27 UTC
当你点击了依据源文件重建向量库就会报错
File "/home/ubuntu/anaconda3/envs/langchain666/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
File "/home/ubuntu/Langchain-Chatchat-master/webui.py", line 70, in <module>
    pages[selected_page]["func"](api)
File "/home/ubuntu/Langchain-Chatchat-master/webui_pages/knowledge_base/knowledge_base.py", line 257, in knowledge_base_page
    empty.progress(d["finished"] / d["total"], f"正在处理： {d['doc']}")
KeyError: 'finished'

**Comment by zdj-1995** [comment] 2023-08-21 09:15
文件就是自带的test.txt

**Comment by adminChina** [comment] 2023-08-21 09:47
#1157

**Comment by adminChina** [comment] 2023-08-21 09:48
#1166 #1162 相同问题

**Comment by liunux4odoo** [comment] 2023-08-21 10:10
Duplicate of #1157, #1166, #1162.

已经修复该bug，请更新到最新代码再试一下。

如果还有问题，请再重开本issue.

**Closed by liunux4odoo** 2023-08-21 10:10 UTC
Labels: bug
