### ISSUE TITLE
初始化知识库python cli.py kb --recreate-vs报错

### ISSUE THREAD

**Issue by lori-kuo** [chatchat-space/Langchain-Chatchat#4600] opened 2024-07-24 08:40 UTC
ERROR    | chatchat.server.knowledge_base.kb_cache.faiss_cache:load_vector_store:140 - Error raised by inference API HTTP code: 404, {"error":"model \"quentinz/bge-large-zh-v1.5\" not found, try pulling it first"} 2024-07-24 16:37:27.802 | ERROR    | chatchat.init_database:worker:61 - 向量库 samples 加载失败。

**Comment by liunux4odoo** [comment] 2024-07-24 13:39
duplicate of #4572

**Closed by liunux4odoo** 2024-07-24 13:39 UTC
Labels: bug
